language: node_js
node_js:
  - '0.10'
  - '0.11'
  - '0.12'
  - 'iojs'
before_install: 'bundle && npm install --global bower jshint && bower install'
before_script: 'jshint client/**/*.js && scss-lint client/**/*.scss'
